/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        primary: 'var(--color-primary)',
        primaryAlt: 'var(--color-primary-alt)',
        secondary: 'var(--color-secondary)',
        secondaryAlt: 'var(--color-secondary-alt)',
        tertiary: 'var(--color-tertiary)',
        tertiaryAlt: 'var(--color-tertiary-alt)',
        background: 'var(--color-background)',
        surface: 'var(--color-surface)',
        surfaceAlt: 'var(--color-surface-alt)',
        text: 'var(--color-text)',
        muted: 'var(--color-text-muted)',
        border: 'var(--color-border)',
        success: 'var(--color-success)',
        warning: 'var(--color-warning)',
        danger: 'var(--color-danger)',
        info: 'var(--color-info)',
        onPrimary: 'var(--color-on-primary)',
        onSecondary: 'var(--color-on-secondary)',
        onSuccess: 'var(--color-on-success)',
        onWarning: 'var(--color-on-warning)',
        onDanger: 'var(--color-on-danger)',
        onSurface: 'var(--color-on-surface)',
        sidebarBackground: 'var(--color-sidebar-background)',
        sidebarText: 'var(--color-sidebar-text)',
        sidebarItem: 'var(--color-sidebar-item)',
        sidebarItemText: 'var(--color-sidebar-item-text)',
        sidebarItemActive: 'var(--color-sidebar-item-active)',
        sidebarItemActiveText: 'var(--color-sidebar-item-active-text)',

        // Keep zombie palette for backwards compatibility if needed during migration
        zombie: {
          blood: 'var(--color-danger)',
          'blood-dark': 'var(--color-danger)',
          green: 'var(--color-primary)',
          'green-light': 'var(--color-secondary)',
          'green-dark': 'var(--color-primary-alt)',
          gray: 'var(--color-surface-alt)',
          'gray-light': 'var(--color-border)',
          'gray-dark': 'var(--color-background)',
          warning: 'var(--color-warning)',
          error: 'var(--color-danger)',
          success: 'var(--color-success)',
        },
        terminal: {
          bg: 'var(--color-background)',
          text: 'var(--color-text)',
          border: 'var(--color-primary)',
        }
      },
      fontFamily: {
        'mono': ['var(--font-family)', 'monospace'],
        'zombie': ['Creepster', 'Nosifer', 'cursive'],
        'stencil': ['Special Elite', 'Courier New', 'monospace'],
      },
      animation: {
        'glitch': 'glitch 1s linear infinite',
        'blood-drip': 'blood-drip 2s ease-in-out infinite',
        'scanner': 'scanner 2s linear infinite',
        'pulse-red': 'pulse-red 2s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'shake': 'shake 0.5s ease-in-out',
        'flicker': 'flicker 3s linear infinite',
      },
      keyframes: {
        glitch: {
          '0%, 100%': { transform: 'translate(0)' },
          '20%': { transform: 'translate(-2px, 2px)' },
          '40%': { transform: 'translate(-2px, -2px)' },
          '60%': { transform: 'translate(2px, 2px)' },
          '80%': { transform: 'translate(2px, -2px)' },
        },
        'blood-drip': {
          '0%': { transform: 'translateY(-100%)', opacity: '0' },
          '50%': { opacity: '1' },
          '100%': { transform: 'translateY(100%)', opacity: '0' },
        },
        scanner: {
          '0%': { transform: 'translateY(-100%)' },
          '100%': { transform: 'translateY(100%)' },
        },
        'pulse-red': {
          '0%, 100%': { opacity: '1' },
          '50%': { opacity: '.5' },
        },
        shake: {
          '0%, 100%': { transform: 'translateX(0)' },
          '10%, 30%, 50%, 70%, 90%': { transform: 'translateX(-5px)' },
          '20%, 40%, 60%, 80%': { transform: 'translateX(5px)' },
        },
        flicker: {
          '0%, 100%': { opacity: '1' },
          '41.99%': { opacity: '1' },
          '42%': { opacity: '0' },
          '43%': { opacity: '0' },
          '43.01%': { opacity: '1' },
          '47.99%': { opacity: '1' },
          '48%': { opacity: '0' },
          '49%': { opacity: '0' },
          '49.01%': { opacity: '1' },
        },
      },
      boxShadow: {
        'zombie': '0 0 20px var(--color-danger)',
        'terminal': '0 0 10px var(--color-primary)',
        'blood': '0 4px 20px var(--color-danger)',
      },
      backgroundImage: {
        'grid-pattern': 'linear-gradient(var(--color-primary) 1px, transparent 1px), linear-gradient(90deg, var(--color-primary) 1px, transparent 1px)',
        'noise': "url('data:image/svg+xml,%3Csvg viewBox=\"0 0 200 200\" xmlns=\"http://www.w3.org/2000/svg\"%3E%3Cfilter id=\"noiseFilter\"%3E%3CfeTurbulence type=\"fractalNoise\" baseFrequency=\"0.9\" numOctaves=\"3\" stitchTiles=\"stitch\"/%3E%3C/filter%3E%3Crect width=\"100%25\" height=\"100%25\" filter=\"url(%23noiseFilter)\"/%3E%3C/svg%3E')",
      },
    },
  },
  plugins: [],
}
