#!/bin/bash
###############################################################################
# Guía Rápida de Implementación - Multi-Instancia PZ
###############################################################################

echo "================================================"
echo "   IMPLEMENTACIÓN MULTI-INSTANCIA"
echo "   Project Zomboid Web Admin"
echo "================================================"
echo ""

echo "PASO 1: Dar permisos al script de instalación"
echo "----------------------------------------------"
echo "cd /opt/pzwebadmin/scripts"
echo "chmod +x setup-new-instance.sh"
echo ""

echo "PASO 2: Ejecutar instalación de nueva instancia"
echo "----------------------------------------------"
echo "./setup-new-instance.sh"
echo ""
echo "Esto creará:"
echo "  - /opt/pzserver-new (nueva instancia)"
echo "  - Servicio systemd: pzomboid-new"
echo "  - Configuración con puertos diferentes"
echo ""

echo "PASO 3: Reiniciar el backend"
echo "----------------------------------------------"
echo "cd /opt/pzwebadmin/backend"
echo "# Detener el proceso actual si está corriendo"
echo "npm install  # Instalar dependencias si es necesario"
echo "npm run dev  # O tu comando de inicio"
echo ""

echo "PASO 4: Acceder a la interfaz web"
echo "----------------------------------------------"
echo "1. Abre tu navegador"
echo "2. Ve a la sección 'Server Control'"
echo "3. Verás el panel 'INSTANCIAS DE SERVIDOR'"
echo "4. Haz clic en 'Activar Instancia' para cambiar"
echo ""

echo "CONFIGURACIÓN DE PUERTOS"
echo "----------------------------------------------"
echo "Instancia Actual:"
echo "  - Juego: 16261"
echo "  - RCON: 27015"
echo ""
echo "Instancia Nueva:"
echo "  - Juego: 16262"
echo "  - RCON: 27016"
echo ""

echo "COMANDOS ÚTILES"
echo "----------------------------------------------"
echo "# Ver estado de instancias"
echo "sudo systemctl status pzomboid"
echo "sudo systemctl status pzomboid-new"
echo ""
echo "# Ver logs"
echo "tail -f /opt/pzserver/logs/server.log"
echo "tail -f /opt/pzserver-new/logs/server.log"
echo ""

echo "FIREWALL (si es necesario)"
echo "----------------------------------------------"
echo "sudo ufw allow 16262/udp  # Puerto de juego nueva instancia"
echo "sudo ufw allow 27016/tcp  # Puerto RCON nueva instancia"
echo ""

echo "================================================"
echo "   Para más información ver MULTI_INSTANCE.md"
echo "================================================"
